### ISSUE TITLE
Plugins can't find riverpod snippets plugin

### ISSUE THREAD

**Issue by 8bitter** [tbm98/flutter-riverpod-live-templates#2]
I attempted searching for 'riverpod' in  the Marketplace using the IntelliJ Plugins Settings Dialog. The dialog displays a 'Nothing found' message.

IntelliJ info:
IntelliJ IDEA 2020.3.1 (Ultimate Edition)
Build #IU-203.6682.168, built on December 29, 2020
Runtime version: 11.0.9.1+11-b1145.63 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 4.15.0-130-generic
GC: ParNew, ConcurrentMarkSweep
Memory: 1979M
Cores: 12
Non-Bundled Plugins: com.dubreuia, Dart, com.ixigua.flutter_asset_iteral, io.flutter, org.jetbrains.kotlin, de.mariushoefler.flutter_enhancement_suite, Pythonid
Current Desktop: ubuntu:GNOME

**Comment by tbm98** [comment]
Yes. Current it will available from 181 to 201 build number. I will try to
support newer version

Vào 3:53, Th 7, 16 thg 1, 2021 8bitter <notifications@github.com> đã viết:

**Comment by tbm98** [comment]
Hi @8bitter,
in version 1.4 now you can search and available in 2020.3
