### ISSUE TITLE
Not compatible with IDEA 2022.2

### ISSUE THREAD

**Issue by rmasarovic** [tbm98/flutter-riverpod-live-templates#61]
Hi its not possible install templates to ide 
Not compatible with the version of your running IDE (IntelliJ IDEA 2022.2)
is it possible fix that?

**Comment by tbm98** [comment]
I'm going to update it. Thanks for your report.

**Comment by tbm98** [comment]
Hi. it is going to live on store. but you can install by pre-built file [here](https://github.com/tbm98/flutter-riverpod-live-templates/suites/7773324254/artifacts/327034030)
