### ISSUE TITLE
2.223.1 broke snippets

### ISSUE THREAD

**Issue by Karmalakas** [tbm98/flutter-riverpod-live-templates#67]
On 2.223.1 typing `cons` suggests only `const`. Had to downgrade to 2.223.0 for snippet suggestions to appear and now `cons` again shows `consumer*`. 

Flutter Plugin v72.1.2
Android Studio Electric Eel | 2022.1.1 Patch 1 Build #AI-221.6008.13.2211.9514443 (managed through JetBrains Toolbox)
Windows 10

**Comment by tbm98** [comment]
Hello. Version 2.223.2 just launch to fix it.

**Comment by Karmalakas** [comment]
Seems to be working
