### ISSUE TITLE
Support 2023.2

### ISSUE THREAD

**Issue by fabiancrx** [tbm98/flutter-riverpod-live-templates#70]
The plugin is not supported in the latest 2023.2 EAP.

Exact version and details:
```
IntelliJ IDEA 2023.2 EAP (Ultimate Edition)
Build #IU-232.6095.10, built on May 17, 2023
```

**Comment by tbm98** [comment]
Thanks!
I will update soon

Vào 00:37, Th 7, ngày 03 tháng 6 năm 2023 fabiancrx <
***@***.***> đã viết:

**Comment by tbm98** [comment]
Hi @fabiancrx.
You can download zip file here https://github.com/tbm98/flutter-riverpod-live-templates/actions/runs/5197400299
or wait for it on plugin store.

**Comment by fabiancrx** [comment]
Thanks tbm98.
